security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            #just to test the cart twig [before authentification---public access]
#            pattern: ^/(?!cart).*$
#            stateless: false
#            # ----
            lazy: true
#            anonymous: lazy
            provider: app_user_provider
            form_login:
                 login_path: app_login
                 check_path: app_login
                 enable_csrf: true
                 default_target_path: app_homepage
                 always_use_default_target_path: false
                 success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false

    access_control:
        - { path: ^/checkout, roles: ROLE_USER }
        - { path: ^/cart, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/search, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }    
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }


