security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_homepage  # Change if you want
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: PUBLIC_ACCESS }    
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/game_creation, roles: PUBLIC_ACCESS}
        - { path: ^/store, roles: PUBLIC_ACCESS}
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
