# Default homepage route
home:
    path: /
    controller: App\Controller\DefaultController::index
app_homepage:
    path: /
    controller: App\Controller\HomeController::index
# Example route for a product page
product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show
    requirements:
        id: '\d+'
logout:
    path: app_logout
# Example route for a contact page
contact:
    path: /contact
    controller: App\Controller\ContactController::index

# Example route for a dashboard
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

# Import routes defined by attributes in controllers
controllers:
    resource: '../src/Controller/'
    type: attribute
app_signin:
    path: /signup
    controller: App\Controller\SignUpController::index
#Route for the library Page
library:
    path: /library
    controller: App\Controller\LibraryController::index
payment_paypal_success:
    path: /payment/paypal/success
    controller: App\Controller\PaymentController::paypalSuccess